= Distributed Lock

Distributed lock ensures your method cannot be run in parallel from multiple JVMs (cluster of servers, microservices, ...).
It uses a common store to keep track of used locks and your method needs to acquire one or more locks to run.

By default, locks follow methods lifecycle. They are obtained at the start of the method and released at the end of the method.
Manual controlling is supported and explained later in this document.

All locks acquired by lock implementations in this project will expire after 10 seconds, timeout after 1 second if unable to acquire lock and sleep for 50 ms between retries.
These options are customizable per annotation.

== Enabling locking

The project contains several configurations and annotations to help you enable locking and customize it.
To enable locking you must first include `@EnableDistributedLock`.
This will import the configuration that will scan all provided `Lock` beans and configure the `LockAdvice`.

Project provides the following out-of-the-box lock implementations:

 - Mongo
 - Redis

=== MongoDB locks

MongoDB locks are provided in the `distributed-lock-mongo` project.
It provides the following `Lock` implementations:

 - `SimpleMongoLock` - lock single key

Include `@EnableMongoDistributedLock` to enable MongoDB locks.

[source,java]
----
@Configuration
@EnableMongoDistributedLock
public class LockConfiguration {
}
----

This will configure standard locks for MongoDB if you have the necessary dependencies on your classpath.
If you are using Spring Boot and Maven simply add these dependencies to your `pom.xml`.

[source,xml]
----
<dependency>
    <groupId>com.github.alturkovic</groupId>
    <artifactId>distributed-lock-mongo</artifactId>
</dependency>
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-mongodb</artifactId>
</dependency>
----

Aliases used:

 - `@MongoLocked` - uses `SimpleMongoLock`

=== Redis locks

Redis locks are provided in the `distributed-lock-redis` project.
It provides the following `Lock` implementations:

 - `SimpleRedisLock` - lock single key
 - `MultiRedisLock` - lock multiple keys

Include `@EnableRedisDistributedLock` to enable Redis locks.

[source,java]
----
@Configuration
@EnableRedisDistributedLock
public class LockConfiguration {
}
----

This will configure standard locks for Redis if you have the necessary dependencies on your classpath.
If you are using Spring Boot and Maven simply add these dependencies to your `pom.xml`.

[source,xml]
----
<dependency>
    <groupId>com.github.alturkovic</groupId>
    <artifactId>distributed-lock-redis</artifactId>
</dependency>
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-redis</artifactId>
</dependency>
----

Aliases used:

 - `@RedisLocked` - uses `SimpleRedisLock`
 - `@RedisMultiLocked` - uses `MultiRedisLock`

== Using locks

To lock your methods you need to first enable locking as described in the previous section.

AOP advice works around the `@Locked` annotation. The `type` field described which implementation of the lock to use.
To prevent repeating yourself if you plan on using the same implementation (as most people usually will), I've added alias support.
They wrap the `@Locked` annotation and define the type used.

Each lock needs to define a https://docs.spring.io/spring/docs/current/spring-framework-reference/html/expressions.html[SpEL] expression used to acquire the lock.
To learn more about Spring aliases visit https://github.com/spring-projects/spring-framework/wiki/Spring-Annotation-Programming-Model[this] link.

=== Manually controlled locks

Sometimes you might want lock to be acquired when calling a specific method and get released only when it expires (throttling).

To acquire a lock that doesn't get released automatically set `manuallyReleased` to `false` on `@Locked` annotation.

For more grained control (e.g., locking in the middle of the method and releasing later in the code), inject the lock in your service and acquire the lock manually.

=== Example

[source,java]
----
@Component
public class Example {

    @Qualifier("simpleRedisLock")
    private Lock lock;

    // other fields...

    private void manuallyLocked() {
        // code before locking...

        final String token = lock.acquire(keys, storeId, expirationTimeUnit, expiration, retryMillis, timeoutTimeUnit, timeout);

        // check if you acquired a token
        if (StringUtils.isEmpty(token)) {
            throw new IllegalStateException("Lock not acquired!");
        }

        // code after locking...

        lock.release(keys, token, storeId);

        // code after releasing the lock...
    }
}
----

=== Unsuccessful locks

If method cannot be locked, `DistributedLockConfiguration` will be thrown.

Method might not acquire the lock if:

. keys from SpEL expression cannot be resolved
. another method acquired the lock
. Lock implementation threw an exception

== Examples

Locking a method with the name _aliased_ in the document called _lock_ in MongoDB:

[source,java]
----
@MongoLocked(expression = "'aliased'", typeSpecificStoreId = "lock")
public void runLockedWithMongo() {
    // locked code
}
----

Locking with multiple keys determined in runtime, use SpEL, for an example:

[source,java]
----
@RedisMultiLocked(expression = "T(com.example.MyUtils).getNamesWithId(#p0)")
public void runLockedWithRedis(final int id) {
    // locked code
}
----

This means that the `runLockedWithRedis` method will execute only if all keys evaluated by expression were acquired.

Locking with a custom lock implementation based on value of integer field `count`:

[source,java]
----
@Locked(type = MyCustomLock.class, expression = "getCount", prefix = "using:")
public void runLockedWithMyCustomLock() {
    // locked code
}
----

== SpEL key generator

This is the default key generator the advice uses. If you wish to use your own, don't use any of the provided configurations,
simply write your own and specify your own `KeyGenerator` implementation and pass it to `LockAdvice`.

The default key generator has access to the currently executing context, meaning you can access your fields and methods from SpEL.
By default, parameters of the method are accessible from SpEL with #p prefix followed by the parameter index, ie: `#p1` is the second parameter.

Examples provided in `com.github.alturkovic.lock.key.SpelKeyGeneratorTest`.

== Customization

If you want to use custom lock implementations, simply implement `Lock` interface and register it in a configuration.
The `LockAdvice` will pick it up and register it automatically.

You can also create an alias for your lock so you don't have to specify `@Locked` type field.
The `LockAdvice` will recognize your alias automatically.

For examples, look at the aliases in the `com.github.alturkovic.lock.annotation.alias` package.